version: '3.7'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /data/k8s-volume/common/timezone/localtime:/etc/localtime:ro
      - /data/k8s-volume/common/timezone/timezone:/etc/timezone:ro
      - /data/k8s-volume/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /data/k8s-volume/nginx/logs/:/var/log/nginx/
      - /data/k8s-volume/wwwroot/:/data/k8s-volume/wwwroot/

networks:
  default:
    external:
      name: mobe-network
