version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /data/k8s-volume/common/timezone/localtime:/etc/localtime:ro
      - /data/k8s-volume/common/timezone/timezone:/etc/timezone:ro
      - /data/k8s-volume/jenkins/jenkins_home:/var/jenkins_home
    domainname: mobe-network

networks:
  default:
    external:
      name: mobe-network
