version: '3'

services:
  verdaccio:
    image: lsw1991abc/verdaccio:ldap.1.0
    container_name: verdaccio
    ports:
      - 4873:4873
    volumes:
      - /data/k8s-volume/common/timezone/timezone:/etc/timezone:ro
      - /data/k8s-volume/verdaccio/conf/:/verdaccio/conf/
      - /data/k8s-volume/verdaccio/plugins/:/verdaccio/plugins/
      - /data/k8s-volume/verdaccio/storage/:/verdaccio/storage/

networks:
  default:
    external:
      name: mobe-network
