version: '3'

services:
  php7fpm:
    image: lsw1991abc/php:7-fpm
    container_name: php7fpm
    ports:
      - 9000:9000
    volumes:
      - /data/k8s-volume/common/timezone/localtime:/etc/localtime:ro
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php.ini:/usr/local/etc/php/php.ini:ro
      - /data/k8s-volume/wwwroot/:/data/k8s-volume/wwwroot/

networks:
  default:
    external:
      name: mobe-network
