version: '3.7'

services:
  redis:
    image: redis:5.0
    container_name: redis
    volumes:
      - /data/k8s-volume/common/timezone/localtime:/etc/localtime:ro
      - /data/k8s-volume/common/timezone/timezone:/etc/timezone:ro
      - /data/k8s-volume/redis/data/:/data/
    domainname: mobe-network
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: mobe-network
